# coding: utf-8

"""
    Analytics Service

    Analytics service for online cinema platform. Collects and analyzes viewing events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.analytics_api import router as AnalyticsApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Analytics Service",
    description="Analytics service for online cinema platform. Collects and analyzes viewing events.",
    version="1.0.0",
)

app.include_router(AnalyticsApiRouter)
app.include_router(DefaultApiRouter)
