# coding: utf-8

"""
    Analytics Service

    Analytics service for online cinema platform. Collects and analyzes viewing events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserStatsResponse(BaseModel):
    """
    User viewing statistics
    """ # noqa: E501
    user_id: StrictStr
    movies_started: StrictInt
    movies_finished: StrictInt
    unique_movies_watched: StrictInt
    total_watch_time_seconds: StrictInt
    completion_rate: Union[StrictFloat, StrictInt]
    period_days: StrictInt
    most_watched_movie_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["user_id", "movies_started", "movies_finished", "unique_movies_watched", "total_watch_time_seconds", "completion_rate", "period_days", "most_watched_movie_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserStatsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if most_watched_movie_id (nullable) is None
        # and model_fields_set contains the field
        if self.most_watched_movie_id is None and "most_watched_movie_id" in self.model_fields_set:
            _dict['most_watched_movie_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserStatsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "movies_started": obj.get("movies_started"),
            "movies_finished": obj.get("movies_finished"),
            "unique_movies_watched": obj.get("unique_movies_watched"),
            "total_watch_time_seconds": obj.get("total_watch_time_seconds"),
            "completion_rate": obj.get("completion_rate"),
            "period_days": obj.get("period_days"),
            "most_watched_movie_id": obj.get("most_watched_movie_id")
        })
        return _obj


