# coding: utf-8

"""
    Payment Service

    Payment processing service for online cinema platform with YooMoney integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.payments_api import router as PaymentsApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Payment Service",
    description="Payment processing service for online cinema platform with YooMoney integration",
    version="1.0.0",
)

app.include_router(PaymentsApiRouter)
app.include_router(DefaultApiRouter)
