# coding: utf-8

"""
    catalog-service

    Movie catalog service with Kafka events

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.movies_api import router as MoviesApiRouter
from openapi_server.apis.movies_admin_api import router as MoviesAdminApiRouter
from openapi_server.apis.movies_public_api import router as MoviesPublicApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="catalog-service",
    description="Movie catalog service with Kafka events",
    version="1.0.0",
)

app.include_router(MoviesApiRouter)
app.include_router(MoviesAdminApiRouter)
app.include_router(MoviesPublicApiRouter)
app.include_router(DefaultApiRouter)
