# coding: utf-8

"""
    Payment Service

    Payment processing service for online cinema platform with YooMoney integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class PaymentStatusEnum(str, Enum):
    """
    Payment status enum
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    PROCESSING = 'processing'
    SUCCEEDED = 'succeeded'
    FAILED = 'failed'
    CANCELLED = 'cancelled'
    REFUNDED = 'refunded'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


