# coding: utf-8

"""
    Payment Service

    Payment processing service for online cinema platform with YooMoney integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.payment_provider_enum import PaymentProviderEnum
from openapi_server.models.payment_status_enum import PaymentStatusEnum
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PaymentResponse(BaseModel):
    """
    Payment response
    """ # noqa: E501
    id: StrictStr
    user_id: StrictStr
    amount: Union[StrictFloat, StrictInt]
    currency: StrictStr
    status: PaymentStatusEnum
    provider: PaymentProviderEnum
    provider_payment_id: Optional[StrictStr] = None
    plan_id: Optional[StrictStr] = None
    subscription_duration_days: Optional[StrictInt] = None
    checkout_url: Optional[StrictStr] = None
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "user_id", "amount", "currency", "status", "provider", "provider_payment_id", "plan_id", "subscription_duration_days", "checkout_url", "created_at", "updated_at", "completed_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if provider_payment_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_payment_id is None and "provider_payment_id" in self.model_fields_set:
            _dict['provider_payment_id'] = None

        # set to None if plan_id (nullable) is None
        # and model_fields_set contains the field
        if self.plan_id is None and "plan_id" in self.model_fields_set:
            _dict['plan_id'] = None

        # set to None if subscription_duration_days (nullable) is None
        # and model_fields_set contains the field
        if self.subscription_duration_days is None and "subscription_duration_days" in self.model_fields_set:
            _dict['subscription_duration_days'] = None

        # set to None if checkout_url (nullable) is None
        # and model_fields_set contains the field
        if self.checkout_url is None and "checkout_url" in self.model_fields_set:
            _dict['checkout_url'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PaymentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "user_id": obj.get("user_id"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "provider": obj.get("provider"),
            "provider_payment_id": obj.get("provider_payment_id"),
            "plan_id": obj.get("plan_id"),
            "subscription_duration_days": obj.get("subscription_duration_days"),
            "checkout_url": obj.get("checkout_url"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "completed_at": obj.get("completed_at")
        })
        return _obj


