# coding: utf-8

"""
    auth-service

    Authentication and authorization service for online cinema platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.authentication_api import router as AuthenticationApiRouter
from openapi_server.apis.health_api import router as HealthApiRouter
from openapi_server.apis.o_auth_api import router as OAuthApiRouter
from openapi_server.apis.root_api import router as RootApiRouter

app = FastAPI(
    title="auth-service",
    description="Authentication and authorization service for online cinema platform",
    version="1.0.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(HealthApiRouter)
app.include_router(OAuthApiRouter)
app.include_router(RootApiRouter)
