# coding: utf-8

"""
    Streaming Service

    Video streaming service with S3/MinIO, signed URLs, and watch progress tracking

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.streaming_api import router as StreamingApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Streaming Service",
    description="Video streaming service with S3/MinIO, signed URLs, and watch progress tracking",
    version="1.0.0",
)

app.include_router(StreamingApiRouter)
app.include_router(DefaultApiRouter)
