# coding: utf-8

"""
    catalog-service

    Movie catalog service with Kafka events

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MovieResponse(BaseModel):
    """
    MovieResponse
    """ # noqa: E501
    title: Annotated[str, Field(strict=True, max_length=500)]
    original_title: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    description: Optional[StrictStr] = None
    year: Annotated[int, Field(le=2100, strict=True, ge=1900)]
    duration: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    poster_url: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    trailer_url: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    rating: Optional[Union[Annotated[float, Field(le=10.0, strict=True, ge=0.0)], Annotated[int, Field(le=10, strict=True, ge=0)]]] = None
    age_rating: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    imdb_id: Optional[Annotated[str, Field(strict=True, max_length=20)]] = None
    id: UUID
    is_published: StrictBool
    published_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["title", "original_title", "description", "year", "duration", "poster_url", "trailer_url", "rating", "age_rating", "imdb_id", "id", "is_published", "published_at", "created_at", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MovieResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if original_title (nullable) is None
        # and model_fields_set contains the field
        if self.original_title is None and "original_title" in self.model_fields_set:
            _dict['original_title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if poster_url (nullable) is None
        # and model_fields_set contains the field
        if self.poster_url is None and "poster_url" in self.model_fields_set:
            _dict['poster_url'] = None

        # set to None if trailer_url (nullable) is None
        # and model_fields_set contains the field
        if self.trailer_url is None and "trailer_url" in self.model_fields_set:
            _dict['trailer_url'] = None

        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if age_rating (nullable) is None
        # and model_fields_set contains the field
        if self.age_rating is None and "age_rating" in self.model_fields_set:
            _dict['age_rating'] = None

        # set to None if imdb_id (nullable) is None
        # and model_fields_set contains the field
        if self.imdb_id is None and "imdb_id" in self.model_fields_set:
            _dict['imdb_id'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['published_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MovieResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "original_title": obj.get("original_title"),
            "description": obj.get("description"),
            "year": obj.get("year"),
            "duration": obj.get("duration"),
            "poster_url": obj.get("poster_url"),
            "trailer_url": obj.get("trailer_url"),
            "rating": obj.get("rating"),
            "age_rating": obj.get("age_rating"),
            "imdb_id": obj.get("imdb_id"),
            "id": obj.get("id"),
            "is_published": obj.get("is_published"),
            "published_at": obj.get("published_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


