# coding: utf-8

"""
    catalog-service

    Movie catalog service with Kafka events

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MovieUpdate(BaseModel):
    """
    MovieUpdate
    """ # noqa: E501
    title: Optional[StrictStr] = None
    original_title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    year: Optional[StrictInt] = None
    duration: Optional[StrictInt] = None
    poster_url: Optional[StrictStr] = None
    trailer_url: Optional[StrictStr] = None
    rating: Optional[Union[StrictFloat, StrictInt]] = None
    age_rating: Optional[StrictStr] = None
    genre_ids: Optional[List[UUID]] = None
    actor_ids: Optional[List[UUID]] = None
    director_ids: Optional[List[UUID]] = None
    __properties: ClassVar[List[str]] = ["title", "original_title", "description", "year", "duration", "poster_url", "trailer_url", "rating", "age_rating", "genre_ids", "actor_ids", "director_ids"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MovieUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if original_title (nullable) is None
        # and model_fields_set contains the field
        if self.original_title is None and "original_title" in self.model_fields_set:
            _dict['original_title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if year (nullable) is None
        # and model_fields_set contains the field
        if self.year is None and "year" in self.model_fields_set:
            _dict['year'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if poster_url (nullable) is None
        # and model_fields_set contains the field
        if self.poster_url is None and "poster_url" in self.model_fields_set:
            _dict['poster_url'] = None

        # set to None if trailer_url (nullable) is None
        # and model_fields_set contains the field
        if self.trailer_url is None and "trailer_url" in self.model_fields_set:
            _dict['trailer_url'] = None

        # set to None if rating (nullable) is None
        # and model_fields_set contains the field
        if self.rating is None and "rating" in self.model_fields_set:
            _dict['rating'] = None

        # set to None if age_rating (nullable) is None
        # and model_fields_set contains the field
        if self.age_rating is None and "age_rating" in self.model_fields_set:
            _dict['age_rating'] = None

        # set to None if genre_ids (nullable) is None
        # and model_fields_set contains the field
        if self.genre_ids is None and "genre_ids" in self.model_fields_set:
            _dict['genre_ids'] = None

        # set to None if actor_ids (nullable) is None
        # and model_fields_set contains the field
        if self.actor_ids is None and "actor_ids" in self.model_fields_set:
            _dict['actor_ids'] = None

        # set to None if director_ids (nullable) is None
        # and model_fields_set contains the field
        if self.director_ids is None and "director_ids" in self.model_fields_set:
            _dict['director_ids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MovieUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "original_title": obj.get("original_title"),
            "description": obj.get("description"),
            "year": obj.get("year"),
            "duration": obj.get("duration"),
            "poster_url": obj.get("poster_url"),
            "trailer_url": obj.get("trailer_url"),
            "rating": obj.get("rating"),
            "age_rating": obj.get("age_rating"),
            "genre_ids": obj.get("genre_ids"),
            "actor_ids": obj.get("actor_ids"),
            "director_ids": obj.get("director_ids")
        })
        return _obj


