# coding: utf-8

"""
    user-service

    User profiles, subscriptions, watch history, and favorites

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WatchHistoryUpdate(BaseModel):
    """
    Schema for updating watch progress.
    """ # noqa: E501
    content_id: UUID
    content_type: StrictStr
    progress_seconds: Annotated[int, Field(strict=True, ge=0)]
    duration_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    completed: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["content_id", "content_type", "progress_seconds", "duration_seconds", "completed"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WatchHistoryUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.duration_seconds is None and "duration_seconds" in self.model_fields_set:
            _dict['duration_seconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WatchHistoryUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "content_id": obj.get("content_id"),
            "content_type": obj.get("content_type"),
            "progress_seconds": obj.get("progress_seconds"),
            "duration_seconds": obj.get("duration_seconds"),
            "completed": obj.get("completed") if obj.get("completed") is not None else False
        })
        return _obj


