# coding: utf-8

"""
    user-service

    User profiles, subscriptions, watch history, and favorites

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.favorites_api import router as FavoritesApiRouter
from openapi_server.apis.history_api import router as HistoryApiRouter
from openapi_server.apis.users_api import router as UsersApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="user-service",
    description="User profiles, subscriptions, watch history, and favorites",
    version="1.0.0",
)

app.include_router(FavoritesApiRouter)
app.include_router(HistoryApiRouter)
app.include_router(UsersApiRouter)
app.include_router(DefaultApiRouter)
