# coding: utf-8

"""
    Notification Service

    Notification service for online cinema platform with Email (SendGrid/AWS SES) and Push (FCM) support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.notifications_api import router as NotificationsApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Notification Service",
    description="Notification service for online cinema platform with Email (SendGrid/AWS SES) and Push (FCM) support",
    version="1.0.0",
)

app.include_router(NotificationsApiRouter)
app.include_router(DefaultApiRouter)
