# coding: utf-8

"""
    Search Service

    Full-text search service for online cinema using Elasticsearch

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.search_api import router as SearchApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Search Service",
    description="Full-text search service for online cinema using Elasticsearch",
    version="1.0.0",
)

app.include_router(SearchApiRouter)
app.include_router(DefaultApiRouter)
